### ISSUE TITLE
Change `https://esi.tech.ccp.is` to `https://esi.evetech.net`

### ISSUE THREAD

**Issue by Ionaru** [ccpgames/esi-swagger-ui#25]
[The `https://esi.tech.ccp.is` URL is going to stop functioning on 2019-01-07](https://developers.eveonline.com/blog/article/removal-of-redirect-from-.tech.ccp.is-on-jan-7th).

Because of this, any mentions of `https://esi.tech.ccp.is` should be replaced with `https://esi.evetech.net` in this repository.

Places I could find are on the [homepage](https://github.com/esi/esi-swagger-ui) and the [wiki](https://github.com/esi/esi-swagger-ui/wiki).

**Comment by lukasni** [comment]
Updated in the wiki, Repo description will have to be changed by CCP.

**Comment by Ionaru** [comment]
Looks like CCP changed it, closing this issue.
